### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by amanairwarrior** [iamsayan/upi-qr-code-payment-for-woocommerce#2]
Plugin Shows Internal Server Error
i am using Wordpress 4.9
PHP 7.2

**Comment by iamsayan** [comment]
4.9. what?

**Comment by amanairwarrior** [comment]
Sir Wordpress Version 4.9

**Comment by amanairwarrior** [comment]
Is this the reason of Internal Server Error

**Comment by iamsayan** [comment]
Hello @amanairwarrior 

You should use Merchant UPI Id instead of regular User UPI ID as per latest NPCI Rules. Thanks.
