### ISSUE TITLE
Threshold limit exceed 

### ISSUE THREAD

**Issue by desidude03** [iamsayan/upi-qr-code-payment-for-woocommerce#3]
I am getting an error only when m browsing my site in mu mobile. When I click on click to pay through upi. I am getting "threshold limit exceeded" in Bhim UPI and Maximum limited exceed by your bank in Google Pay.

**Comment by iamsayan** [comment]
Hello @desidude03 

You should use Merchant UPI Id instead of regular User UPI ID as per latest NPCI Rules. Thanks.
