### ISSUE TITLE
Payment Through Link Not Working

### ISSUE THREAD

**Issue by raunix** [iamsayan/upi-qr-code-payment-for-woocommerce#4]
When we are trying to make payments by using link "click here to pay through upi" payment got failed with an error kindly check onces and update please

**Comment by desidude03** [comment]
Well even m facing same problem. Would be glad if this issue get resolved. The problem occurs when the reverse request from upi apps. Check it once with SSL enabled sites as my project right now is NON SSL

**Comment by iamsayan** [comment]
Hello @desidude03 @raunix 

You should use Merchant UPI Id instead of regular User UPI ID as per latest NPCI  Rules. Thanks.
